#collector.yaml in the root directory
#Set an environment variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/collector.yaml'

processors:
  batch:
    send_batch_max_size: 10000
    timeout: 10s
  attributes:
    actions:
      - key: environment
        value: localhost
        action: insert

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${env:NR_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [debug, otlphttp]
  telemetry:
    metrics:
      address: localhost:8888